In [3]:
import h3
import pandas as pd
import pyarrow
import geopandas
import h3pandas

res = 7

In [4]:
alerts_df = geopandas.read_file("wssc_alerts_geocoded.shp")
alerts_df.head()

,Unnamed:_0,title,date,pipe_diame,address,corrected_,full_text,geocode_qu,latitude,longitude,geocode_st,geometry
0,0,Emergency Water Main Repair - Takoma Park,"December 30, 2022",8,"602 Ethan Allen Avenue, Takoma Park","602 Ethan Allen Avenue, Takoma Park","Laurel, MD â December 30, 2022: WSSC Water i...","602 Ethan Allen Avenue, Takoma Park, Maryland,...",38.976122,-76.996519,ok,POINT (-76.99652 38.97612)
1,1,Emergency Water Main Repair - Capitol Heights,"December 29, 2022",12,"6180 Old Central Avenue, Rollins Avenue, Capit...","6180 Old Central Avenue, Rollins Avenue, Capit...","Laurel, MD â December 29, 2022: WSSC Water i...","6180 Old Central Avenue, Rollins Avenue, Capit...",38.886057,-76.903669,ok,POINT (-76.90367 38.88606)
2,2,Emergency Water Main Repair - Oxon Hill,"December 29, 2022",8,"801 Owens Road, Oxon Hill","801 Owens Road, Oxon Hill","Laurel, MD â December 29, 2022: WSSC Water i...","801 Owens Road, Oxon Hill, Maryland, USA",38.824928,-76.995675,ok,POINT (-76.99568 38.82493)
3,3,Emergency Water Main Repair - Silver Spring,"December 28, 2022",8,"12001 Old Columbia Pike, Silver Spring","12001 Old Columbia Pike, Silver Spring","Laurel, MD â December 28, 2022: WSSC Water i...","12001 Old Columbia Pike, Silver Spring, Maryla...",39.052508,-76.976358,ok,POINT (-76.97636 39.05251)
4,4,Emergency Water Main Repair - Greenbelt,"December 28, 2022",10,"9115 Springhill Ln, Greenbelt","9115 Springhill Ln, Greenbelt","Laurel, MD â December 28, 2022: WSSC Water i...","9115 Springhill Ln, Greenbelt, Maryland, USA",39.002690,-76.903941,ok,POINT (-76.90394 39.00269)

In [5]:
path = "MDOT_SHA_Annual_Average_Daily_Traffic/MDOT_SHA_Annual_Average_Daily_Traffic_(AADT)_Segments.shp"
traffic_df = geopandas.read_file(path)
traffic_df.head()

/home/emmaf/miniconda3/lib/python3.13/site-packages/pyogrio/raw.py:200: UserWarning: Measured (M) geometry types are not supported. Original type 'Measured 3D LineString' is converted to 'LineString Z'
  return ogr_read(

,LOCATION_I,COUNTY_ID,COUNTY_DES,MUN_SORT,MUNICIPALI,ROADNAME,ID_PREFIX,ID_RTE_NO,MP_SUFFIX,ID_MP,...,AADT_2020,AAWDT_2020,AADT_2021,AAWDT_2021,AADT_2022,AAWDT_2022,GlobalID,AADT_2023,AAWDT_2023,geometry
0,S2010020163,2.0,ANNE ARUNDEL,0.0,NONE,RAMP 1 FR IS 695 NB TO MD 969A WB,RP,695.0,NaN,0.10,...,2694.0,2834.0,3055.0,3155.0,3085.0,3185.0,3f9c1e3e-14b2-49ff-a2ba-fe24ad3de7e4,3300.0,3400.0,"LINESTRING Z (-8533878.226 4754055.515 0, -853..."
1,V2013000888,2.0,ANNE ARUNDEL,0.0,NONE,RAMP 2 FR MD 665 WB TO MD 2 NB,RP,665.0,NaN,-1.00,...,7110.0,7680.0,8141.0,8711.0,8192.0,8852.0,e8f900f6-5e14-47aa-94c8-f5f336c98cf7,8333.0,8833.0,"LINESTRING Z (-8520236.533 4717590.884 0, -852..."
2,S2004020043,2.0,ANNE ARUNDEL,0.0,NONE,RAMP 2 FR US 50 WB TO BAY DALE DR NB,RP,50.0,NaN,0.14,...,1172.0,1272.0,1343.0,1443.0,1354.0,1464.0,15ddf5c2-748d-483d-a853-64d28688bdc1,1375.0,1465.0,"LINESTRING Z (-8513241.661 4724883.517 0, -851..."
3,S2006020059,2.0,ANNE ARUNDEL,0.0,NONE,RAMP 6 FR MD 198 EB TO MD 32 SB,RP,32.0,NaN,0.10,...,8842.0,9552.0,10123.0,10833.0,10184.0,11004.0,3273b5cb-d571-4a4a-b212-f625e2e18496,10345.0,10975.0,"LINESTRING Z (-8544565.635 4734550.112 0, -854..."
4,S2010020150,2.0,ANNE ARUNDEL,0.0,NONE,RAMP 1 FR CATHERINE AVE TO RAMP 8(MD100),RP,100.0,NaN,0.01,...,1294.0,1404.0,1485.0,1595.0,1495.0,1625.0,c2b2b41f-ed20-44f9-ab0a-eb95427ac7fc,1320.0,1400.0,"LINESTRING Z (-8521280.966 4739199.965 0, -852..."

In [6]:
traffic_df.to_wkt().loc[0]["geometry"]

'LINESTRING Z (-8533878.226 4754055.5151 0, -8533863.2808 4754049.5083 0, -8533851.0262 4754042.6814 0, -8533841.8433 4754035.4549 0, -8533836.6884 4754025.0371 0, -8533833.264 4754012.3548 0, -8533829.6457 4753994.7745 0)'

In [8]:
traffic_df.h3.geo_to_h3_aggregate(resolution=res,operation="count")

ValueError: x attribute access only provided for Point geometries